version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Backend__Url=http://backend:8082
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - frontend-keys:/home/app/.aspnet/DataProtection-Keys

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
    depends_on:
      - mssql
    networks:
      - app-network
    volumes:
      - backend-keys:/home/app/.aspnet/DataProtection-Keys

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-keys:
  backend-keys:
  mssql-data: